# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: State-led finance research
    url: '#thesis'
    weight: 20
  - name: Other ongoing research
    url: '#research'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Teaching
    url: '#teaching'
    weight: 50
  - name: CV
    url: uploads/Katharina-Fleiner-CV.pdf
    weight: 60
  - name: Contact me
    weight: 70
    url: '#contact'



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  